### ISSUE TITLE
Problems with pizpalue and powermail

### ISSUE THREAD

**Issue by schorsch8878** [buepro/typo3-pizpalue#3]
Hello,

I use Pizpalue Template 11.3.0 and Powermail 8.1.2 in TYPO3 10.4.6. In a empty Introduction Package there are no problems and Powermail send a Email with all content from the fields. With pizpalue the emails from powermail are empty! The succes page is empty too. 

is this Problem aware?

Many Thanks

**Comment by buepro** [comment]
Per default pizpalue configures the RTE parse function to interprete `{}` as data of type `getText` (see [manual](https://docs.typo3.org/p/buepro/typo3-pizpalue/master/en-us/User/Various.html#data-from-type-gettext)). Since powermail has its own use this conflicts. 

**Corrective action:**
1. Create an extension template on the page where powermail is installed
1. Add `lib.parseFunc_RTE.nonTypoTagStdWrap.insertData = 0` to the templates setup

*Remark: In case `getText` type substitution isn't needed on the site the TS setup might be added to the sites root template.*

![Pizpalue_Powermail](https://user-images.githubusercontent.com/37214997/91881384-b5028900-ec81-11ea-9405-4ea3c8e2419f.jpg)

**Comment by schorsch8878** [comment]
Hello, many thanks for this Tipp! On the success page it works, but the emails from powermail are still empty. There must be another bug.....

**Comment by buepro** [comment]
On my test environment the following static templates are used:

![Pizpalue_Powermail_IncludeStatic](https://user-images.githubusercontent.com/37214997/91982099-0c5c3400-ed2a-11ea-8b53-14233081a99f.jpg)

With this setup the emails contain the field data.

**Comment by schorsch8878** [comment]
Hello, when i add the powermail template before the pizpalue template, it works! 

Many thanks
